services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.kinky-thots.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail-data:/var/mail
      - ./mail-state:/var/mail-state
      - ./mail-logs:/var/log/mail
      - ./config:/tmp/docker-mailserver
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - OVERRIDE_HOSTNAME=mail.kinky-thots.com
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.kinky-thots.com
      - ENABLE_FAIL2BAN=1
      - ENABLE_RSPAMD=1
      - ENABLE_OPENDKIM=0
      - RSPAMD_LEARN=1
      - POSTFIX_MESSAGE_SIZE_LIMIT=26214400
      - ENABLE_QUOTAS=1
      - SPOOF_PROTECTION=1
      - ENABLE_UPDATE_CHECK=1
      - SUPERVISOR_LOGLEVEL=warn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
